linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gosec
    - gochecknoglobals
    - lll
linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 15
issues:
  exclude-use-default: false
