linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gosec
    - gochecknoglobals
    - lll
linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
