env:
  - GO111MODULE=on
builds:
  -
    main: ./cmd/blkinfo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/blp1526/blkinfo.version={{.Version}} -X github.com/blp1526/blkinfo.revision={{.Commit}}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
